version: 2
updates:
- package-ecosystem: nuget
  directory: /src/GraphWebhooks/
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  open-pull-requests-limit: 10
